title: PRG Icària. Receptari Python
description: Petites receptes de codi en Pyhton per a la matèria Programació de 1r de batxillerat a l'institut Icària de Barcelona.
 theme: just-the-docs

# theme: jekyll-theme-minimal
